
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed Apr 24 15:18:44 CST 2024
//----------------------------------------------------

package code;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int DESPLAZAMIENTO_IZQUIERDA = 68;
  public static final int SHORT = 24;
  public static final int SIGNED = 25;
  public static final int ENTEROS = 83;
  public static final int DIVISION = 49;
  public static final int MENOR_QUE = 52;
  public static final int CONST = 6;
  public static final int XOR_BINARIO = 57;
  public static final int MODULO_Y_ASIGNACION = 66;
  public static final int SUMA_ASIGNACION = 61;
  public static final int REGISTER = 22;
  public static final int ENUM = 14;
  public static final int DIVISION_ASIGNACION = 65;
  public static final int SIZEOF = 26;
  public static final int MENOR_O_IGUAL_QUE = 67;
  public static final int MAYOR_QUE = 53;
  public static final int DOUBLE = 12;
  public static final int STRUCT = 28;
  public static final int LLAMADA_A_FUNCION = 76;
  public static final int BRACKET_RIGHT = 44;
  public static final int ASIGNACION_AND = 72;
  public static final int OR_BINARIO = 56;
  public static final int COMPLEMENTO_A_UNO = 59;
  public static final int FLOAT = 16;
  public static final int GOTO = 18;
  public static final int DOS_PUNTOS = 86;
  public static final int ASIGNACION_XOR = 75;
  public static final int DIFERENTE_QUE = 71;
  public static final int STRINGS = 41;
  public static final int NEGACION_LOGICA = 54;
  public static final int BOOLS = 37;
  public static final int INTS = 39;
  public static final int PUNTO_COMA = 84;
  public static final int ASIGNACION_DESPLAZAMIENTO_IZQUIERDA = 79;
  public static final int CLASS = 11;
  public static final int LIB = 36;
  public static final int INCLUDE = 10;
  public static final int INCREMENTO = 60;
  public static final int COMA = 85;
  public static final int MODULO = 51;
  public static final int PRINTF = 45;
  public static final int CHARS = 40;
  public static final int LONG = 21;
  public static final int IGUAL = 82;
  public static final int WHILE = 35;
  public static final int UNION = 31;
  public static final int RESTA_ASIGNACION = 63;
  public static final int CHAR = 5;
  public static final int MAYOR_O_IGUAL_QUE = 69;
  public static final int SWITCH = 29;
  public static final int DO = 9;
  public static final int FOR = 17;
  public static final int VOID = 33;
  public static final int DECREMENTO = 64;
  public static final int EXTERN = 15;
  public static final int RETURN = 23;
  public static final int ELSE = 13;
  public static final int BREAK = 3;
  public static final int DESPLAZAMIENTO_DERECHA = 70;
  public static final int INT = 20;
  public static final int VAR_NAME = 81;
  public static final int FLOATS = 38;
  public static final int COMPARACION_TRES_SENTIDOS = 78;
  public static final int EOF = 0;
  public static final int DEFAULT = 8;
  public static final int PARENTHESES_LEFT = 46;
  public static final int SUMA = 50;
  public static final int MAIN = 42;
  public static final int OR = 74;
  public static final int error = 1;
  public static final int MULTIPLIACION_Y_ASIGNACION = 77;
  public static final int IGUAL_QUE = 62;
  public static final int RESTA = 48;
  public static final int CONTINUE = 7;
  public static final int LIST = 87;
  public static final int IF = 19;
  public static final int UNSIGNED = 32;
  public static final int ASIGNACION_DESPLAZAMIENTO_DERECHA = 80;
  public static final int MULTIPLICACION = 58;
  public static final int BRACKET_LEFT = 43;
  public static final int VOLATILE = 34;
  public static final int PARENTHESES_RIGHT = 47;
  public static final int CASE = 4;
  public static final int AND_BINARIO = 55;
  public static final int AND = 73;
  public static final int STATIC = 27;
  public static final int TYPEDEF = 30;
  public static final int AUTO = 2;
}

