
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed Feb 21 15:09:50 CST 2024
//----------------------------------------------------

package sintatico;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int STRINGS = 42;
  public static final int SHORT = 24;
  public static final int CHARS = 41;
  public static final int CONST = 6;
  public static final int CHAR = 5;
  public static final int VARS = 37;
  public static final int CASE = 4;
  public static final int DOUBLE = 12;
  public static final int CONTINUE = 7;
  public static final int INT = 20;
  public static final int REGISTER = 22;
  public static final int FOR = 17;
  public static final int BRACKET_RIGHT = 45;
  public static final int BRACKET_LEFT = 44;
  public static final int STATIC = 27;
  public static final int SIZEOF = 26;
  public static final int IGUAL = 49;
  public static final int CLASS = 11;
  public static final int EXTERN = 15;
  public static final int TYPEDEF = 30;
  public static final int MAIN = 43;
  public static final int IF = 19;
  public static final int PUNTO_COMA = 51;
  public static final int EOF = 0;
  public static final int RETURN = 23;
  public static final int error = 1;
  public static final int BOOLS = 38;
  public static final int INCLUDE = 10;
  public static final int UNSIGNED = 32;
  public static final int AUTO = 2;
  public static final int ENTEROS = 50;
  public static final int BREAK = 3;
  public static final int PARENTHESES_RIGHT = 48;
  public static final int VOID = 33;
  public static final int PRINTF = 46;
  public static final int INTS = 40;
  public static final int SWITCH = 29;
  public static final int LIB = 36;
  public static final int UNION = 31;
  public static final int ELSE = 13;
  public static final int SIGNED = 25;
  public static final int ENUM = 14;
  public static final int GOTO = 18;
  public static final int WHILE = 35;
  public static final int LOGIN = 21;
  public static final int DEFAULT = 8;
  public static final int FLOAT = 16;
  public static final int PARENTHESES_LEFT = 47;
  public static final int VOLATILE = 34;
  public static final int FLOATS = 39;
  public static final int STRUCT = 28;
  public static final int DO = 9;
}

